### PR TITLE
Updated software licensing statement

### PR DESCRIPTION
**Pull request by tkphd**
The Director's statements have all been updated. Transcribed current language and updated README link.

### CODE REVIEW

**Comment by ianhbell** [comment]
Whoah this is a big and positive change.  Any idea if it holds also for international?

**Comment by tkphd** [comment]
International IP law is a quagmire, and IANAL! I have no idea :exploding_head:

**Comment by ianhbell** [comment]
Agreed, just thought with this change maybe bigger changes were afoot

**Comment by ianhbell** [comment]
Any idea who made those changes to the page?

**Comment by tkphd** [comment]
«replied offline»

**Comment by wd15** [comment]
Do you have a link to the Director's statements?

**Comment by wd15** [comment]
No worries, the link is in the README file.

**Review by wd15 — APPROVED** [review]

**Comment by wd15** [comment]
This bit "...provided that this notice and disclaimer of warranty appears in all copies" is now effectively "Modified works should carry a notice stating that you changed the software and should note the date and nature of any such change. Please explicitly acknowledge the National Institute of Standards and Technology as the source of the software.", which is less restrictive. Is that a correct interpretation?

**Comment by ajnelson-nist** [comment]
Hello, all.  Is this text still awaiting something to merge?  I am working through licensing revisions and would like to not commit to changes that are between minutes or days from being outdated.

**Comment by tkphd** [comment]
Nope, with @wd15's approving review it was only waiting for me to click the Merge button. Please go ahead and update your license files.

**Pull request merged**
